# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: [workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2


      - name: Azure Login
        uses: Azure/login@v1
        with:
          # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: create virtual network
        uses: Azure/cli@v1
        with:
          # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
#       - name: Deploy to Azure Container Instances
#         uses: Azure/aci-deploy@release-bug-fix
#         with:
#           inlineScript: |
#               az network vnet create -g ACI-DEPLOY -n aci-deploy-vnet-test


#           # The DNS Name Label for Container with Public IP
# #           dns-name-label: kp-url-for-container
#           ip-address: Private
#           # Specify the fully qualified container image name. For example, "myregistry.azurecr.io/nginx:latest" or "python:3.7.2-alpine/"
#           image: nginx

#           location: 'centralus'

#           # Name of the Container Group Instance
#           name: aci-deploy-test




