# This is a basic workflow to help you get started with Actions

name: testin_table

on: [workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: 'Generate Dashboard'
      id: dashboard
      uses: ethomson/issue-dashboard@v1
      with:
        config: |
          title: 'Dashboard'
          output:
            format: html
            filename: 'index.html'
          setup: |
              userdata.values = async function(repo,label) {
                function sleep(milliseconds) {
                  const date = Date.now();
                  let currentDate = null;
                  do {
                    currentDate = Date.now();
                  } while (currentDate - date < milliseconds);
                }
                sleep(2000)
                const repo1 = repo
                const label1 = label
                var results;
                if(label === "") {
                    results = await github.search.issuesAndPullRequests(
                    { q: `repo:${repo1} is:pr is:open` }
                    )
                }
                else if(label === "stale") {
                    results = await github.search.issuesAndPullRequests(
                    { q: `repo:${repo1} is:pr is:open created:<${date("-90 days")}`}
                    )
                }
                else{
                  results = await github.search.issuesAndPullRequests(
                  { q: `repo:${repo1} is:pr is:open label:${label1}`}
                  )
                }
                if(results.data.items.length === 0){
                  return '0'
                }
                else{
                  return results.data.total_count 
                }
              }
              userdata.urls = async function(repo,label) {
                function sleep(milliseconds) {
                  const date = Date.now();
                  let currentDate = null;
                  do {
                    currentDate = Date.now();
                  } while (currentDate - date < milliseconds);
                }
                sleep(2000)
                const repo1 = repo
                var prlink;
                if(label === "") {
                  prlink = 'https://github.com/'+repo+'/pulls?q=is%3Apr+is%3A'+'open'
                }
                else if(label === "stale") {
                  var today = new Date();
                  var myPastDate=new Date(today);
                  myPastDate.setDate(myPastDate.getDate() - 90);
                  var staledate = myPastDate.toISOString().split("T")[0];
                  prlink = 'https://github.com/'+repo+'/pulls?q=is%3Apr+is%3A'+'open'+'created%3A<'+staledate+'+'
                  
                }
                else{
                  prlink = 'https://github.com/'+repo+'/pulls?q=is%3Apr+is%3A'+'open'+'label%3A'+label
                }
                return prlink
              } 
          sections:
          - title: 'label-wise'
            widgets:
            - type: 'table'
              title: 'label-wise'
              headers:
              - 'action'
              - 'open issues'
              - 'need-to-triage'
              - 'enhancement'
              - 'question'
              - 'bug'
              - 'documentation'
              - 'performance-issue'
              - 'waiting-for-customer'
              - 'external-dependency'
              - 'idle(inactive>14days)'
              - 'stale(90 days old)'
              elements:
              - - value: 'Azure login'
                - value: '{{ userdata.values("Azure/login","") }}'
                  url: '{{ userdata.urls("Azure/login","") }}'
                - value: '{{ userdata.values("Azure/login","need-to-triage") }}'
                  url: '{{ userdata.urls("Azure/login","need-to-triage") }}'
                - value: '{{ userdata.values("Azure/login","enhancement") }}'
                  url: '{{ userdata.urls("Azure/login","enhancement") }}'
                - value: '{{ userdata.values("Azure/login","question") }}'
                  url: '{{ userdata.urls("Azure/login","question") }}'
                - value: '{{ userdata.values("Azure/login","bug") }}'
                  url: '{{ userdata.urls("Azure/login","bug") }}'
                - value: '{{ userdata.values("Azure/login","documentation") }}'
                  url: '{{ userdata.urls("Azure/login","documentation") }}'
                - value: '{{ userdata.values("Azure/login","performance-issue") }}'
                  url: '{{ userdata.urls("Azure/login","performance-issue") }}'
                - value: '{{ userdata.values("Azure/login","waiting-for-customer") }}'
                  url: '{{ userdata.urls("Azure/login","waiting-for-customer") }}'
                - value: '{{ userdata.values("Azure/login","external-dependency") }}'
                  url: '{{ userdata.urls("Azure/login","external-dependency") }}'
                - value: '{{ userdata.values("Azure/login","idle") }}'
                  url: '{{ userdata.urls("Azure/login","idle") }}'
                - value: '{{ userdata.values("Azure/login","stale") }}'
                  url: '{{ userdata.urls("Azure/login","stale") }}'
                 
              - - value: 'webapps-deploy'
                - value: '{{ userdata.values("Azure/webapps-deploy","") }}'
                  url: '{{ userdata.urls("Azure/webapps-deploy","") }}'
                - value: '{{ userdata.values("Azure/webapps-deploy","need-to-triage") }}'
                  url: '{{ userdata.urls("Azure/webapps-deploy","need-to-triage") }}'
                - value: '{{ userdata.values("Azure/webapps-deploy","enhancement") }}'
                  url: '{{ userdata.urls("Azure/webapps-deploy","enhancement") }}'
                - value: '{{ userdata.values("Azure/webapps-deploy","question") }}'
                  url: '{{ userdata.urls("Azure/webapps-deploy","question") }}'
                - value: '{{ userdata.values("Azure/webapps-deploy","bug") }}'
                  url: '{{ userdata.urls("Azure/webapps-deploy","bug") }}'
                - value: '{{ userdata.values("Azure/webapps-deploy","documentation") }}'
                  url: '{{ userdata.urls("Azure/webapps-deploy","documentation") }}'
                - value: '{{ userdata.values("Azure/webapps-deploy","performance-issue") }}'
                  url: '{{ userdata.urls("Azure/webapps-deploy","performance-issue") }}'
                - value: '{{ userdata.values("Azure/webapps-deploy","waiting-for-customer") }}'
                  url: '{{ userdata.urls("Azure/webapps-deploy","waiting-for-customer") }}'
                - value: '{{ userdata.values("Azure/webapps-deploy","external-dependency") }}'
                  url: '{{ userdata.urls("Azure/webapps-deploy","external-dependency") }}'
                - value: '{{ userdata.values("Azure/webapps-deploy","idle") }}'
                  url: '{{ userdata.urls("Azure/webapps-deploy","idle") }}'
                - value: '{{ userdata.values("Azure/webapps-deploy","stale") }}'
                  url: '{{ userdata.urls("Azure/webapps-deploy","stale") }}'
              - - value: 'aci-deploy'
                - value: '{{ userdata.values("Azure/aci-deploy","") }}'
                  url: '{{ userdata.urls("Azure/aci-deploy","") }}'
                - value: '{{ userdata.values("Azure/aci-deploy","need-to-triage") }}'
                  url: '{{ userdata.urls("Azure/aci-deploy","need-to-triage") }}'
                - value: '{{ userdata.values("Azure/aci-deploy","enhancement") }}'
                  url: '{{ userdata.urls("Azure/aci-deploy","enhancement") }}'
                - value: '{{ userdata.values("Azure/aci-deploy","question") }}'
                  url: '{{ userdata.urls("Azure/aci-deploy","question") }}'
                - value: '{{ userdata.values("Azure/aci-deploy","bug") }}'
                  url: '{{ userdata.urls("Azure/aci-deploy","bug") }}'
                - value: '{{ userdata.values("Azure/aci-deploy","documentation") }}'
                  url: '{{ userdata.urls("Azure/aci-deploy","documentation") }}'
                - value: '{{ userdata.values("Azure/aci-deploy","performance-issue") }}'
                  url: '{{ userdata.urls("Azure/aci-deploy","performance-issue") }}'
                - value: '{{ userdata.values("Azure/aci-deploy","waiting-for-customer") }}'
                  url: '{{ userdata.urls("Azure/aci-deploy","waiting-for-customer") }}'
                - value: '{{ userdata.values("Azure/aci-deploy","external-dependency") }}'
                  url: '{{ userdata.urls("Azure/aci-deploy","external-dependency") }}'
                - value: '{{ userdata.values("Azure/aci-deploy","idle") }}'
                  url: '{{ userdata.urls("Azure/aci-deploy","idle") }}'
                - value: '{{ userdata.values("Azure/aci-deploy","stale") }}'
                  url: '{{ userdata.urls("Azure/aci-deploy","stale") }}'
                  
        token: ${{ github.token }}

    - name: Commit files
      id: commit
      run: |
        git config --local user.email "kanika1894@github.com"
        git config --local user.name "kanika1894"
        git add --all
        if [-z "$(git status --porcelain)"]; then
           echo "::set-output name=push::false"
        else
           git commit -m "Add changes" -a
           echo "::set-output name=push::true"
        fi
      shell: bash
 
    - name: Push changes
      if: steps.commit.outputs.push == 'true'
      uses: ad-m/github-push-action@master
      with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
