name: mainpage
'on':
  - workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Generate Dashboard
        id: dashboard
        uses: ethomson/issue-dashboard@v1
        with:
          config: |
            title: 'Health Dashboard'
            output:
              format: html
              filename: 'mainpage.html'
            setup: | 
                  item.count = async function(itemType,label) {
                    const repos = 'repo:Azure/login repo:Azure/aci-deploy'
                    var results
                    if(label === "") {
                        results = await github.search.issuesAndPullRequests(
                        { q: `${repos} is:${itemType} is:open`}
                        )
                    }
                    else if(label === "stale") {
                      results = await github.search.issuesAndPullRequests(
                      { q: `${repos} is:${itemType} is:open created:<${date("-90 days")}`}
                      )
                    } 
                    else if(label === "closed") {
                      results = await github.search.issuesAndPullRequests(
                      { q: `${repos} is:${itemType} is:closed`}
                      )
                    }
                    else{
                      results = await github.search.issuesAndPullRequests(
                      { q: `${repos} is:${itemType} is:open label:${label}`}
                      )
                    }
                    if(results.data.items.length === 0){
                      return '0'
                    }
                    else{
                      return results.data.total_count 
                    }
                  }
                  
                  item.url = async function(itemType,label) {
                    const repos = 'repo:Azure/login repo:Azure/aci-deploy'
                    var prlink;
                    if(label === "") {
                      prlink = 'https://github.com/search?q='+ repos + '+is%3A'+ itemType + '+is%3Aopen'
                    }
                    else if(label === "stale") {
                      var today = new Date();
                      var myPastDate=new Date(today);
                      myPastDate.setDate(myPastDate.getDate() - 90);
                      var staledate = myPastDate.toISOString().split("T")[0];
                      prlink = 'https://github.com/search?q=' + repos + '+is%3A' + itemType + '+is%3Aopen' + '+created%3A<'+ staledate
                    }
                    else if(label === "closed") {
                      prlink = 'https://github.com/search?q='+ repos + '+is%3A' + itemType + '+is%3Aclosed'
                    }
                    else{
                      prlink = 'https://github.com/search?q='+ repos + '+is%3A'+ itemType + '+is%3Aopen' + '+label%3A' + label
                    }
                    return prlink
                  } 

            sections:
            - title: 'Issues'
              widgets:
              - type: 'number'
                title: 'Idle issues(inactive >14days)'
                value: '{{ item.count("issue","idle") }}'
                url: '{{ item.url("issue","idle") }}'
              - type: 'number'
                title: 'P0 bugs'
                value: '{{ item.count("issue","P0") }}'
                url: '{{ item.url("issue","P0") }}'
              - type: 'number'
                title: 'P1 bugs'
                value: '{{ item.count("issue","P1") }}'
                url: '{{ item.url("issue","P1") }}'
              - type: 'number'
                title: 'Enhancements'
                value: '{{ item.count("issue","enhancement") }}'
                url: '{{ item.url("issue","enhancement") }}'
              - type: 'number'
                title: 'Total issues'
                value: '{{ item.count("issue","") }}'
                url: '{{ item.url("issue","") }}'
                
            - title: 'PRs'
              widgets:
              - type: 'number'
                title: 'Open'
                value: '{{ item.count("pr","") }}'
                url: '{{ item.url("pr","") }}'
              - type: 'number'
                title: 'Idle (inactive >14days)'
                value: '{{ item.count("pr","idle") }}'
                url: '{{ item.url("pr","idle") }}'
              - type: 'number'
                title: 'Stale (90 days old)'
                value: '{{ item.count("pr","stale") }}'
                url: '{{ item.url("pr","stale") }}' 
              - type: 'number'
                title: 'Closed'
                value: '{{ item.count("pr","closed") }}'
                url: '{{ item.url("pr","closed") }}'
                
            - title: 'Details'
              widgets:
              - type: 'string'
                value: 'Issues detailed information'
                url: 'https://kanika1894.github.io/kp-aci-deploy'
              - type: 'string'
                value: 'PR detailed information'
                url: 'https://kanika1894.github.io/kp-aci-deploy/pr.html'

          token: '${{ github.token }}'
      - name: Commit files
        id: commit
        run: |
          git config --local user.email "kanika1894@github.com"
          git config --local user.name "kanika1894"
          git pull
          git add --all
          if [-z "$(git status --porcelain)"]; then
             echo "::set-output name=push::false"
          else
             git commit -m "Add changes" -a
             echo "::set-output name=push::true"
          fi
        shell: bash
      - name: Push changes
        if: steps.commit.outputs.push == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
