name: mainpage
'on':
  - workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Generate Dashboard
        id: dashboard
        uses: ethomson/issue-dashboard@v1
        with:
          config: |
            title: 'Summary4'
            output:
              format: html
              filename: 'mainpage.html'
            setup: | 
                  userdata.values = async function(itemType,label) {
                    const repos = 'repo:Azure/login repo:Azure/aci-deploy'
                    const filter = label
                    const item = itemType
                    var results
                    if(label === "") {
                        results = await github.search.issuesAndPullRequests(
                        { q: `${repos} is:${item} is:open`}
                        )
                    }
                    else if(label === "stale") {
                      results = await github.search.issuesAndPullRequests(
                      { q: `${repos} is:${item} is:open created:<${date("-90 days")}`}
                      )
                    } 
                    else if(label === "closed") {
                      results = await github.search.issuesAndPullRequests(
                      { q: `${repos} is:${item} is:closed`}
                      )
                    }
                    else{
                      results = await github.search.issuesAndPullRequests(
                      { q: `${repos} is:${item} is:open label:${filter}`}
                      )
                    }
                    if(results.data.items.length === 0){
                      return '0'
                    }
                    else{
                      return results.data.total_count 
                    }
                  }
                  
                  userdata.pullurl = async function(label) {
                    const repos = 'repo:Azure/login repo:Azure/aci-deploy'
                    var prlink;
                    if(label === "") {
                      prlink = 'https://github.com/search?q='+ repos + '+is%3Apr'+ '+is%3Aopen'
                    }
                    else if(label === "stale") {
                      var today = new Date();
                      var myPastDate=new Date(today);
                      myPastDate.setDate(myPastDate.getDate() - 90);
                      var staledate = myPastDate.toISOString().split("T")[0];
                      prlink = 'https://github.com/search?q=' + repos + '+is%3Apr' + '+is%3Aopen' + '+created%3A<'+ staledate+'+'
                    }
                    else if(label === "closed") {
                      prlink = 'https://github.com/search?q='+ repos + '+is%3Apr'+ '+is%3Aclosed'
                    }
                    else{
                      prlink = 'https://github.com/search?q='+ repos + '+is%3Apr'+ '+is%3Aopen' + '+label%3A' + label
                    }
                    return prlink
                  } 

            sections:
            - title: 'Issues'
              widgets:
              - type: 'number'
                title: 'Total issues'
                value: '{{ userdata.values("issue","") }}'
              - type: 'number'
                title: 'Idle issues(inactive >14days)'
                value: '{{ userdata.values("issue","idle") }}'
              - type: 'number'
                title: 'P0 bugs'
                value: '{{ userdata.values("issue","P0") }}'
              - type: 'number'
                title: 'P1 bugs'
                value: '{{ userdata.values("issue","P1") }}'
              - type: 'number'
                title: 'Enhancements'
                value: '{{ userdata.values("issue","enhancement") }}'
                
            - title: 'PRs'
              widgets:
              - type: 'number'
                title: 'Open'
                value: '{{ userdata.values("pr","") }}'
                url: '{{ userdata.pullurl("") }}'
              - type: 'number'
                title: 'Idle (inactive >14days)'
                value: '{{ userdata.values("pr","idle") }}'
                url: '{{ userdata.pullurl("idle") }}'
              - type: 'number'
                title: 'Stale (90 days old)'
                value: '{{ userdata.values("pr","stale") }}'
                url: '{{ userdata.pullurl("stale") }}'
              - type: 'number'
                title: 'Closed'
                value: '{{ userdata.values("pr","closed") }}'
                url: '{{ userdata.pullurl("closed") }}'
                    
          token: '${{ github.token }}'
      - name: Commit files
        id: commit
        run: |
          git config --local user.email "kanika1894@github.com"
          git config --local user.name "kanika1894"
          git pull
          git add --all
          if [-z "$(git status --porcelain)"]; then
             echo "::set-output name=push::false"
          else
             git commit -m "Add changes" -a
             echo "::set-output name=push::true"
          fi
        shell: bash
      - name: Push changes
        if: steps.commit.outputs.push == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
