# This is a basic workflow to help you get started with Actions

name: pr-counter

on: [workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: 'Generate Dashboard'
      id: dashboard
      uses: ethomson/issue-dashboard@v1
      with:
        config: |
          title: 'PR Dashboard sections update'
          output:
            format: html
            filename: 'pr.html'
          setup: |
                userdata.count = async function(repo,label) {
                  const criteria = (label==="closed")? "closed" : "open"
                  var results;
                  if(label === "" || label === "closed") {
                      results = await github.search.issuesAndPullRequests(
                      { q: `repo:${repo} is:pr is:${criteria}` }
                      )
                  }
                  else if(label === "stale") {
                      results = await github.search.issuesAndPullRequests(
                      { q: `repo:${repo} is:pr is:${criteria} created:<${date("-90 days")}`}
                      )
                  }
                  else{
                    results = await github.search.issuesAndPullRequests(
                    { q: `repo:${repo} is:pr is:${criteria} label:${label}`}
                    )
                  }
                  if(results.data.items.length === 0){
                    return '0'
                  }
                  else{
                    return results.data.total_count 
                  }
                }
                userdata.url = async function(repo,label) {
                  const criteria = (label==="closed")? "closed" : "open"
                  var url;
                  if(label === "" || label === "closed") {
                  url = 'https://github.com/'+repo+'/pulls?q=is%3Apr+is%3A'+criteria
                  }
                  else if(label === "stale") {
                    var today = new Date();
                    var PastDate=new Date(today);
                    PastDate.setDate(PastDate.getDate() - 90);
                    var staledate = PastDate.toISOString().split("T")[0];
                    url = 'https://github.com/' + repo + '/pulls?q=is%3Apr+is%3A' + criteria + '+created%3A<'+staledate+'+'

                  }
                  else{
                    url = 'https://github.com/'+repo+'/pulls?q=is%3Apr+is%3A'+criteria+'+label%3A'+label
                  }
                  return url
                } 
              
          sections:
          - title: 'PR'
            widgets:
            - type: 'table'
              title: 'actions wise PRs'
              headers:
              - 'Action'
              - 'Open PR'
              - 'Stale PR(90 days old)'
              - 'Idle PR(inactive > 14 days)'	
              - 'Closed PR'
              elements:
              - - value:'Azure login
                - value:'{{ userdata.count("Azure/login","") }}'
                  url:'{{ userdata.url("Azure/login","") }}'
                - value:'{{ userdata.count("Azure/login","stale") }}'
                  url:'{{ userdata.url("Azure/login","stale") }}'
                - value:'{{ userdata.count("Azure/login","idle") }}'
                  url:'{{ userdata.url("Azure/login","idle") }}'
                - value:'{{ userdata.count("Azure/login","closed") }}'
                  url:'{{ userdata.url("Azure/login","closed") }}'
              - - value:'webapps-deploy'
                - value:'{{ userdata.count("Azure/webapps-deploy","") }}'
                  url:'{{ userdata.url("Azure/webapps-deploy","") }}'
                - value:'{{ userdata.count("Azure/webapps-deploy","stale") }}'
                  url:'{{ userdata.url("Azure/webapps-deploy","stale") }}'
                - value:'{{ userdata.count("Azure/webapps-deploy","idle") }}'
                  url:'{{ userdata.url("Azure/webapps-deploy","idle") }}'
                - value:'{{ userdata.count("Azure/webapps-deploy","closed") }}'
                  url:'{{ userdata.url("Azure/webapps-deploy","closed") }}'
              - - value:'aci-deploy'
                - value:'{{ userdata.count("Azure/aci-deploy","") }}'
                  url:'{{ userdata.url("Azure/aci-deploy","") }}'
                - value:'{{ userdata.count("Azure/aci-deploy","stale") }}'
                  url:'{{ userdata.url("Azure/aci-deploy","stale") }}'
                - value:'{{ userdata.count("Azure/aci-deploy","idle") }}'
                  url:'{{ userdata.url("Azure/aci-deploy","idle") }}'
                - value:'{{ userdata.count("Azure/aci-deploy","closed") }}'
                  url:'{{ userdata.url("Azure/aci-deploy","closed") }}'
              
          
                    
        token: ${{ github.token }}

    - name: Commit files
      id: commit
      run: |
        git config --local user.email "kanika1894@github.com"
        git config --local user.name "kanika1894"
        git add --all
        if [-z "$(git status --porcelain)"]; then
           echo "::set-output name=push::false"
        else
           git commit -m "Add changes" -a
           echo "::set-output name=push::true"
        fi
      shell: bash
 
    - name: Push changes
      if: steps.commit.outputs.push == 'true'
      uses: ad-m/github-push-action@master
      with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
