# This is a basic workflow to help you get started with Actions

name: pr-counter

on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: 'Generate Dashboard'
      id: dashboard
      uses: ethomson/issue-dashboard@v1
      with:
        config: |
          title: 'PR Dashboard sections update'
          output:
            format: html
            filename: 'pr.html'
          setup: |
              userdata.values = async function(repo,label) {
                const repo1 = repo
                const label1 = label
                var results;
                if(label === "") {
                    results = await github.search.issuesAndPullRequests(
                    { q: `repo:${repo1} is:pr is:open label:${label1}`}
                    )
                }
                else if(label === "stale") {
                    results = await github.search.issuesAndPullRequests(
                    { q: `repo:${repo1} is:pr is:open created:<{{ date("-90 days") }}`}
                    )
                }
                else{
                  results = await github.search.issuesAndPullRequests(
                  { q: `repo:${repo1} is:pr is:open label:${label1}`}
                  )
                }
                if(results.data.items.length === 0){
                  return '0'
                }
                else{
                  return results.data.total_count 
                }
              }
              userdata.urls = async function(repo,label) {
                const repo1 = repo
                if(label === "") {
                  const prlink = 'https://github.com/'+repo+'/pulls?q=is%3Apr+is%3Aopen'
                }
                else if(label === "stale") {
                  var today = new Date();
                  var myPastDate=new Date(today);
                  myPastDate.setDate(myPastDate.getDate() - 90);
                  var staledate = myPastDate.toISOString().split("T")[0];
                  const prlink = 'https://github.com/'+repo+'/pulls?q=is%3Apr+is%3Aopen+created%3A>'+staledate+'+'
                  
                }
                
                const prlink = 'https://github.com/'+repo+'/pulls?q=is%3Apr+is%3Aopen+label%3A'+label
                return prlink
              } 
              
          sections:
          - title: 'PR'
            widgets:
            - type: 'table'
              title: 'actions wise PRs'
              headers:
              - 'action'
              - 'total open PR'
              - 'stale PR'
              - 'Idle PR'	
              elements:
              - - value: 'Azure login'
                - value: '{{ userdata.values("Azure/login","") }}'
                  url: '{{ userdata.urls("Azure/login","") }}'
                - value: '{{ userdata.values("Azure/login","stale") }}'
                  url: '{{ userdata.urls("Azure/login","stale") }}'
                - value: '{{ userdata.values("Azure/login","idle") }}'
                  url: '{{ userdata.urls("Azure/login","idle") }}'
          
                    
        token: ${{ github.token }}

    - name: Commit files
      id: commit
      run: |
        git config --local user.email "kanika1894@github.com"
        git config --local user.name "kanika1894"
        git add --all
        if [-z "$(git status --porcelain)"]; then
           echo "::set-output name=push::false"
        else
           git commit -m "Add changes" -a
           echo "::set-output name=push::true"
        fi
      shell: bash
 
    - name: Push changes
      if: steps.commit.outputs.push == 'true'
      uses: ad-m/github-push-action@master
      with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
