name: 'Label Actions'

on:
  issues:
    types: [labeled]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/label-actions@v2
        with:
          github-token: ${{ github.token }}
          config-path: 'setting-labels.yml'
          process-only: ''
